[package]
name = "github-admonition"
version = "0.1.0"
entrypoint = "github-admonition.typ"
authors = ["Flandia Yingman"]
license = "MIT"
description = "Adds GitHub-style Admonitions (Alerts) to Typst."
repository = "https://github.com/FlandiaYingman/typst-github-admonition"
keywords = ["github", "admonition", "alert"]
exclude = ["example.typ"]