[package]
name = "note-me"
version = "0.2.0"
entrypoint = "note-me.typ"
authors = ["Flandia Yingman"]
license = "MIT"
description = "Adds GitHub-style Admonitions (Alerts) to Typst."
repository = "https://github.com/FlandiaYingman/note-me"
keywords = ["github", "admonition", "alert"]
exclude = [".gitignore", "example.typ"]